((.clean) ) hylo@hylo-gaming:~/dev/ordo$ [tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]
[tool.ruff]: command not found
line-length: command not found
target-version: command not found
[tool.ruff.lint]: command not found
-bash: syntax error near unexpected token `["E",'
ignore: command not found
