name: UI CI

on:
  push:
    paths:
      - "ui/ordo-ui/**"
  pull_request:
    paths:
      - "ui/ordo-ui/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui/ordo-ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
